### ISSUE TITLE
DG Review

### ISSUE THREAD

**Issue by bentohset** [AY2324S1-CS2113-F11-2/tp#126]
Overall content wise is good! Just need abit more work on your formatting:
1. Need to have different kinds of UML diagrams (cover all 3 types) in the DG as what i mentioned in class earlier
2. Try to standardize the formatting of your sequence diagrams (same color, same style, color for the classes)
3. Remove all the placeholders (image below) happens in most places.
![image](https://github.com/AY2324S1-CS2113-F11-2/tp/assets/115091471/e4a0d9da-346b-4324-b9e0-adceb3f3996c)

4. Architecture diagram empty
![image](https://github.com/AY2324S1-CS2113-F11-2/tp/assets/115091471/5bf922ea-dfac-49c5-b446-793ef6230bd4)

5. Fix table of contents
![image](https://github.com/AY2324S1-CS2113-F11-2/tp/assets/115091471/53b20575-3be1-4cea-9cd2-9ea0fd0e1ea8)

6. Some formatting error? Perhaps you meant to use the code block which is enclosed in 3 backticks `.
![image](https://github.com/AY2324S1-CS2113-F11-2/tp/assets/115091471/f38907aa-8147-4b2a-9a39-dc1c17ae4890)

**Comment by kaijie0102** [comment]
Addressed
