### ISSUE TITLE
[PE-D][Tester B] Output not shown

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#128]
When user inputs view r/RECIPE_ID or view r/RECIPE_TITLE with a dummy recipe title or id, no output is provided. It may be optimal for the error to be handled, and an error command informing user that "no such recipe is present" can be returned.

![image.png](https://raw.githubusercontent.com/WooKaiNing/ped/main/files/4b90c0d0-64a8-430c-8c41-ebecedc075a5.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: WooKaiNing/ped#1

**Comment by kaijie0102** [comment]
Fixed by #151
