### ISSUE TITLE
Edit ingredient invalid format error handling

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#129]
For edit i/ command, if user inputs a parameter that is not INGREDIENT_NAME, for instance an integer index, the program terminates. Team may wish to handle behaviour of incorrect command.

![Screenshot 2023-11-03 at 4.40.08 PM.png](https://raw.githubusercontent.com/WooKaiNing/ped/main/files/853c9ba2-353e-49bf-acda-6233c8e286e9.png)
Screenshot 2023-11-03 at 4.40.08 PM

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: WooKaiNing/ped#2

**Comment by Haoyuli2002** [comment]
<img width="399" alt="Screenshot 2023-11-10 at 13 02 33" src="https://github.com/AY2324S1-CS2113-F11-2/tp/assets/139958049/b402d327-a25c-47c3-bb10-32c08fd58a1c">
should works now, so you can just edit your ingredients by giving the name of your ingredients
