### ISSUE TITLE
[PE-D][Tester E] Incorrect link

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#131]
![image.png](https://raw.githubusercontent.com/yicheng-toh/ped/main/files/f3300909-a643-44c6-a66a-a7b1022abc29.png)
Link does not access to a download page.

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yicheng-toh/ped#2

**Comment by kaijie0102** [comment]
Fixed by #137
