### ISSUE TITLE
[PE-D][Tester D] Command add r/ duplication error

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#146]
Expected behaviour: Prevent user from adding 2 instances of the same recipe name (i.e. 2 instances of "scramble egg") by throwing an exception

Observed behaviour: Program allows user to add duplicates without throwing any exceptions. Program takes first instance of the duplicate (lowest index)

Possible complications when viewing the recipe via view r/<recipe-name>

Existing fix - view r/index_of_recipe. However, this fix may be rudimentary and given that there’s 2 ways of viewing, it may become very confusing for the user. 

![Screenshot 2023-11-03 at 2.18.20 PM.jpg](https://raw.githubusercontent.com/yeo-menghan/ped/main/files/75ff7417-2a90-4a75-8d3c-3909914630f9.jpg)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: yeo-menghan/ped#4

**Comment by kaijie0102** [comment]
Closes with #158
