### ISSUE TITLE
[PE-D][Tester B] Improvement to filter command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#149]
Team may wish to make filter command case-insensitive.

![image.png](https://raw.githubusercontent.com/WooKaiNing/ped/main/files/32f446ea-1807-4a9c-954b-e432404e5a9d.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: WooKaiNing/ped#4

**Comment by kaijie0102** [comment]
Closed by #158
