### ISSUE TITLE
[PE-D][Tester D] Command Edit - edit r/ s/<out of bounds>

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#157]
Reproduce bug:
1. add r/toast s/1 i/corn,1,pc
2. view r/toast
3. edit r/toast s/2

Expected behaviour: Handle exception to suggest using a smaller step number and return "incorrect format" and prompt another new input
Observed behaviour: Exception thrown and program is ended

![Screenshot 2023-11-03 at 5.09.38 PM.png](https://raw.githubusercontent.com/yeo-menghan/ped/main/files/baffef15-f6be-48b4-bd56-3826d276bb9d.png)

-------------
Labels: `type.FunctionalityBug` `severity.High`
original: yeo-menghan/ped#7

**Comment by charkty** [comment]
Closes with #179
