### ISSUE TITLE
[PE-D][Tester A] Recipe accepts null String

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#159]
![image.png](https://raw.githubusercontent.com/Cazh1/ped/main/files/9b5cf3fa-f71c-4b0b-aa92-0363fea73dff.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Cazh1/ped#4

**Comment by Haoyuli2002** [comment]
Seems that it has already been solved
![Uploading Screenshot 2023-11-10 at 12.53.00.png…]()
