### ISSUE TITLE
[PE-D][Tester E] Conflicting messages

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#161]
![image.png](https://raw.githubusercontent.com/yicheng-toh/ped/main/files/b8bee0ff-c047-42d7-a3a3-819342c9599d.png)
Conflicting statement. Should the user able to proceed?
Can be replicated with zero ingredients.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: yicheng-toh/ped#14

**Comment by charkty** [comment]
Closes with #173
