### ISSUE TITLE
[PE-D][Tester B] Error in edit command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#163]
Edit recipe command does not seem to work. Even though scramble egg recipe exists, it is not found when edit r/ command is used. Alternatively, may want to provide more detailed explanation in UG with respect to how this command can be used.

![image.png](https://raw.githubusercontent.com/WooKaiNing/ped/main/files/bbaaf704-177c-4a9e-ac50-c71e1ca1fa23.png)

-------------
Labels: `severity.High` `type.FeatureFlaw`
original: WooKaiNing/ped#7

**Comment by kaijie0102** [comment]
Closes with #174
