### ISSUE TITLE
[PE-D][Tester C] Error message when editing recipe steps

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#164]
The output is the same as UG with the addition of "Format is incorrect message". The "to: buy" should probably be "to: buy ingredients"?

![image.png](https://raw.githubusercontent.com/ryan1604/ped/main/files/03ce12cb-5260-4eda-990d-5b1c669f71d5.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: ryan1604/ped#4

**Comment by charkty** [comment]
Closes with #174
