### ISSUE TITLE
[PE-D][Tester D] start recipe - unexpected error line

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#166]
Error: Extra error line - “Start your recipe again after getting the above ingredients!” when all ingredients are already satisfied

![Screenshot 2023-11-03 at 3.20.59 PM.jpg](https://raw.githubusercontent.com/yeo-menghan/ped/main/files/37736eb1-34d5-4615-a8eb-6a737c832468.jpg)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yeo-menghan/ped#10

**Comment by charkty** [comment]
Close with #173
