### ISSUE TITLE
[PE-D][Tester D] Recipe list - 5 minutes hard-coded

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#175]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
Error: Confusing to users why it’s hard-coded as 5 minutes duration.

![Screenshot 2023-11-03 at 2.13.02 PM.jpg](https://raw.githubusercontent.com/yeo-menghan/ped/main/files/abd29361-5b79-4eb5-990b-df28999362df.jpg)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: yeo-menghan/ped#16

**Comment by kaijie0102** [comment]
fixed
