### ISSUE TITLE
[PE-D][Tester A] Unable to specify ingredient to edit 

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#181]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/Cazh1/ped/main/files/5fcbbe92-24d7-43f2-a112-2e3b256c4a21.png)
The user to not be able to specify the ingredient with the same name to edit. This is an issue when the user has recipes using the same name but diff quantities. Example (Chicken rice requires 150g chicken while KFC family bucket requires 6 Chicken pieces).

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: Cazh1/ped#6

**Comment by charkty** [comment]
Close with #209
