### ISSUE TITLE
[PE-D][Tester C] List command included in UG but no such command in the program

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#186]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
I assume the command is not supposed to be in the UG?

![image.png](https://raw.githubusercontent.com/ryan1604/ped/main/files/e4a5716b-40a7-4dd3-9401-2ead8d1f253f.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: ryan1604/ped#7

**Comment by kaijie0102** [comment]
Command not in documentation, he might be referring to "help" command
