### ISSUE TITLE
[PE-D][Tester E] Invalid command in UG

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#188]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/yicheng-toh/ped/main/files/efb89210-ea34-4fea-9276-ab2a8317d7e6.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: yicheng-toh/ped#20

**Comment by charkty** [comment]
Same as #196
