### ISSUE TITLE
[PE-D][Tester E] Lack of output after edit command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#190]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/yicheng-toh/ped/main/files/5be7c9ee-530b-470f-acef-96d3f3e58daa.png)

After the command `edit i/bread`.

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: yicheng-toh/ped#21

**Comment by Haoyuli2002** [comment]
I think this issue has already been solved
