### ISSUE TITLE
[PE-D][Tester B] Documentation error in UG

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#196]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
Documentation error in UG- edit i/INGREDIENT_NAME is repeated

![image.png](https://raw.githubusercontent.com/WooKaiNing/ped/main/files/cca37ff3-64fd-4eb1-ae77-6b608960e9a8.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: WooKaiNing/ped#16

**Comment by kaijie0102** [comment]
Require new line
