### ISSUE TITLE
[PE-D][Tester A] Recipe not saved after exit command

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#199]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/Cazh1/ped/main/files/d8888be8-0568-44be-af87-b5c09c291c70.png)

![image.png](https://raw.githubusercontent.com/Cazh1/ped/main/files/2d094d1a-9899-4af2-9a08-bf98d3df4fce.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: Cazh1/ped#10

**Comment by StanleyW00** [comment]
Testers does not create recipe, so it makes sense the `recipe.txt` is empty.
