### ISSUE TITLE
[PE-D][Tester A] Attempting to delete appears to delete the same item twice

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S1-CS2113-F11-2/tp#202]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/Cazh1/ped/main/files/d6b48c29-bb2d-4707-9acc-7ddd7dbfc569.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Cazh1/ped#13

**Comment by charkty** [comment]
Delete milk is a wrong format so it will not delete. Not a bug.
