### ISSUE TITLE
[PE-D][Tester A] Ingredient quantity accepts null String

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S1-CS2113-F11-2/tp#205]
**Note from the teaching team:** This bug was reported during the _Part II (Evaluating Documents)_ stage of the PE. **You may reject this bug if it is not related to the quality of documentation.**<hr>
![image.png](https://raw.githubusercontent.com/Cazh1/ped/main/files/d4468de7-4460-47a3-af5d-e1cc85e3916a.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: Cazh1/ped#16

**Comment by kaijie0102** [comment]
Fixed by #211
